sudo: required

services:
  - docker

before_install:
- docker pull bash:latest
- docker pull bash:4
- docker pull bash:3

script:
- "docker run --rm -it -v $(pwd):/go2dir bash:latest /go2dir/tests/go2dir_tests.sh"
- "docker run --rm -it -v $(pwd):/go2dir bash:3      /go2dir/tests/go2dir_tests.sh"
- "docker run --rm -it -v $(pwd):/go2dir bash:4      /go2dir/tests/go2dir_tests.sh"
