language: c

os:
  - osx
  - precise
  - trusty

before_install:
  - if [[ ! "$TRAVIS_OS_NAME" == "osx" ]]; then sudo apt-get install -qqy curl; fi

script:
  - bash --version
  - ./tests/tesht/tesht.sh ./tests/*.tsh
