# sudo: required
#
# services:
#   - docker
#
# before_install:
# - docker pull bash:latest
# - docker pull bash:4
# - docker pull bash:3
#
# script:
# - "docker run -it --rm -v `pwd`:/`basename $(pwd)` -w /`basename $(pwd)` bash:latest ./tests/tesht/tesht.sh './tests/*.tsh'"
# - "docker run -it --rm -v `pwd`:/`basename $(pwd)` -w /`basename $(pwd)` bash:4 ./tests/tesht/tesht.sh './tests/*.tsh'"
# - "docker run -it --rm -v `pwd`:/`basename $(pwd)` -w /`basename $(pwd)` bash:3 ./tests/tesht/tesht.sh './tests/*.tsh'"

language: c
os:
  - osx
  - linux

before_install:
  - [[ ! "$TRAVIS_OS_NAME" == "osx" ]] && sudo apt-get install -qqy curl

script:
  - echo "$TRAVIS_OS_NAME"
  - bash --version
  - which bash
  - ./tests/tesht/tesht.sh ./tests/*.tsh
